changelog:
  categories:
    - title: 仙劍奇俠傳
      labels:
        - "Game: 仙劍奇俠傳"

    - title: 新仙劍奇俠傳
      labels:
        - "Game: 新仙劍奇俠傳"

    - title: 軒轅劍外傳 - 楓之舞
      labels:
        - "Game: 軒轅劍外傳 - 楓之舞"

    - title: Other Changes
      labels:
        - "*"
